account/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.views import logout,login
from account import  views
urlpatterns = [
    url(r'^login/$', login, {'template_name':'account/login.html',}, name='login'),
    url(r'^logout/$',logout, {'next_page': reverse_lazy('frontend:homepage')}, name='logout'),
    url(r'^signup/$',views.user_registration, name='signup'),
    url(r'^profile/$', views.choose_profile, name='choose_profile' ),

]

healthstone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('platformfrontend.urls', namespace='frontend')),
    url(r'^account/',include('account.urls', namespace='account')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthstone/templates/base/footer.inc.html
<footer class="footer">
				<div class="footer-top padd-top padd-bottom">
					<div class="container">
						<div class="row">
							<div class="col-sm-5">
								<div  class="footer-padd">
									<h6>Quick Links</h6>
								</div>
								<div class="row">
									<div class="col-sm-5">
										<ul>
											<li>
												<a href="index.html">Home</a>
											</li>
											<li>
												<a href="about-us.html">about us</a>
											</li>
											<li>
												<a href="services.html">services</a>
											</li>
											<li>
												<a href="doctors-grid.html">doctors</a>
											</li>
											<li>
												<a href="testimonials.html">testimonial</a>
											</li>
											<li>
												<a href="book-appointment.html">book appointment</a>
											</li>
										</ul>
									</div>
									<div class="col-sm-6">
										<ul>
											<li>
												<a href="departments.html">departments</a>
											</li>
											<li>
												<a href="faq.html">faq</a>
											</li>
											<li>
												<a href="gallery.html">news</a>
											</li>
											<li>
												<a href="blog.html">blog</a>
											</li>
											<li>
												<a href="contact-us.html">contact us</a>
											</li>
											<li>
												<a href="careers.html">careers</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="col-sm-3">
								<div  class="footer-padd">
									<h6>Opening Hours</h6>
								</div>
								<ul class="opening-msg common-padd-bottom">
									<li>
										<span class="opening-hours days">monday - friday</span>
										<span class="opening-hours">8.00 – 17.00</span>
									</li>
									<li>
										<span class="opening-hours days">saturday</span>
										<span class="opening-hours">9.30 – 17.30</span>
									</li>
									<li>
										<span class="opening-hours days">sunday</span>
										<span class="opening-hours">9.30 – 15.00</span>
									</li>
								</ul>
								<ul class="social">
									<li>
										<a href="#" class="social-links">facebook</a>
									</li>
									<li>
										<a href="#" class="social-links">twitter</a>
									</li>
									<li>
										<a href="#" class="social-links">linkedin</a>
									</li>
								</ul>
							</div>
							<div class="col-sm-3 col-sm-offset-1">
								<div  class="footer-padd">
									<h6>contact us</h6>
								</div>
								<address class="footer-address">
									<div class="address-section">
										<span class="address-title">address</span><span class="address-details"> Megahealth Hospital
											Birmingham Street
											Engl, B3 2EW </span>
									</div>
									<div class="address-section">
										<span class="address-title">email</span>
										<a href="mailto:info@megahealth.com" class="address-details">info@megahealth.com</a>
									</div>
									<div class="address-section">
										<span class="address-title">phone</span>
										<a href="tel:85655564555" class="address-details">8565 5564 555</a>
									</div>
								</address>
							</div>
						</div>
					</div>
				</div>
				<div class="footer-bottom">
					<div class="container">
						<div class="row">
							<div class="form-section">
								<div class="newsletter">
									<h6>newsletter</h6>
									<span class="footer-bottom-content">Subscribe your newsletter</span>
								</div>
								<div class="footer-form">
									<form  action="#" method="post">
										<input type="text" name="search" class="input-section"/>
										<input type="submit" value="subscribe" class="submit-button"/>
									</form>
								</div>
							</div>
							<span class="footer-bottom-content">2016 © allright reserved Megahealth</span>
						</div>
					</div>
				</div>
			</footer>

healthstone/templates/base/main_manager.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %} {% endblock %}
    </title>
    {#		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">#}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/layers.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/navigation.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/settings.css' %}" media="screen"/>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=PT+Serif:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700%7COpen+Sans:400,300%7CLibre+Baskerville:400,400italic'
          rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/owl.carousel.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/simple-line-icons.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/global.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/responsive.css' %}" media="screen"/>
    <link href="{% static 'assets/css/skin.less' %}" rel="stylesheet/less">
    <style>
        .form_label {
            width: 100%;
            margin-bottom: 6px;
        }

        .form-pack {
            margin-bottom: 20px;
        }
        .c-white{
            color:white;
        }
        .form_error {
            width: 100%;
            color: yellow;
            font-size: 13px;
        }
    </style>
    {% block css %} {% endblock %}

</head>
<!--Content Area End-->
<body>
<!--Page loader Start-->
<div class="loader">
    <div class="sk-circle">
        <div class="sk-circle1 sk-child"></div>
        <div class="sk-circle2 sk-child"></div>
        <div class="sk-circle3 sk-child"></div>
        <div class="sk-circle4 sk-child"></div>
        <div class="sk-circle5 sk-child"></div>
        <div class="sk-circle6 sk-child"></div>
        <div class="sk-circle7 sk-child"></div>
        <div class="sk-circle8 sk-child"></div>
        <div class="sk-circle9 sk-child"></div>
        <div class="sk-circle10 sk-child"></div>
        <div class="sk-circle11 sk-child"></div>
        <div class="sk-circle12 sk-child"></div>
    </div>
</div>
<div id="wrapper">
    <!--Footer Section Start-->
    <header class="main-header" id="header">
        <div class="container clearfix header-upper-section">
            <a href="index.html" class="header-logo">
                <figure><img src="{% static 'assets/images/logo.png' %}" alt="logo-image"/>
                </figure>
                <span class="txt-wraper"> <strong>Mega Health</strong> <span>premium theme</span> </span> </a>
            <div class="header-contact-details">
                <span class="call-details"> <span class="tel-details">call us</span> <a href="tel:85655564555"
                                                                                        class="tel">8565 5564 555</a> </span>
                <span class="email-details"> <span class="mail-details">email us</span> <a
                        href="mailto:info@megahealth.com" class="mail">info@megahealth.com</a> </span>
            </div>
        </div>
        {% include 'base/nav.inc.html' %}
    </header>
    {% block banner_section %}

    {% endblock %}
    {% block content %}

    {% endblock %}
    {% include 'base/footer.inc.html' %}
    <!--Footer Section End-->
</div>
<!--container Start-->
<!--Page Wrapper End-->
<script type="text/javascript" src="{% static 'assets/js/jquery-1.12.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery-ui.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/owl.carousel.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/less.js' %}"></script>
<!-- revolution slider Js -->
<script type="text/javascript" src="{% static 'assets/js/jquery.themepunch.tools.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.themepunch.revolution.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.revolution-one.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'assets/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/extensions/revolution.extension.navigation.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/extensions/revolution.extension.parallax.min.js' %}"></script>
<!--  revolution slider Js -->
<script type="text/javascript" src="{% static 'assets/js/site.js' %}"></script>
{% block js %} {% endblock %}
</body>
</html>

healthstone/templates/base/nav.inc.html
<div class="nav-section">
					<div class="container">
						<div class="row">
							<nav class="navbar navbar-default">
								<!-- Brand and toggle get grouped for better mobile display -->
								<div class="navbar-header">
									<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
										<span class="sr-only">Toggle navigation</span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
									</button>
								</div>
								<!-- Collect the nav links, forms, and other content for toggling -->
								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
									<ul class="nav navbar-nav">
										<li><a href="{% url 'frontend:homepage' %}">Home</a> </li>
                                        {% if not request.user.is_authenticated %}
                                            <li><a href="{% url 'account:signup' %}">Register</a> </li>
										    <li><a href="{% url 'account:login' %}">Login</a> </li>

                                        {% else %}
										    <li><a href="{% url 'account:logout' %}">Logout</a> </li>
                                        {% endif %}
									</ul>
								</div><!-- /.navbar-collapse -->
							</nav>
							<span class="quick-link"> <span class="quick-link-content">quick links</span> <a href="contact-us.html" class="dot-links"> <span class="spans"> </span> <span class="spans"> </span><span class="spans"> </span> <span class="spans"> </span> <span class="spans"> </span><span class="spans"> </span> <span class="spans"> </span> <span class="spans"> </span> <span class="spans"> </span> </a> </span>
						</div>
					</div>
				</div>